### ISSUE TITLE
Why minimim window size so large?

### ISSUE THREAD

**Issue by JackKnifed** [hashtag-include/slacky#6]
Why is the minimum window size 1100x700 ?

I'm guessing you have a specific reason, I personally like to go with a tall thin window, but my window width is actually 800x1390. However, I cannot go to that width because the default width is higher?

I mean, changing this to suit one user's needs (esp when I can just use something else) is probably silly, but I'm also not seeing the reason for that default - so I thought I'd ask, or see about changing it.

:smile:

**Comment by trjast** [comment]
Ah man yeah I can imagine that's super annoying, and there honestly there wasn't much thought which went into deciding the minimum size other than that it looked the best when testing. I'll update it with a smaller minimum size.

**Comment by trjast** [comment]
Okay, I just published a new version to the store which changes the minimum size from 1100x700 to 765x300 and it should be live within the next hour or so. I hope this fixes your issue, because I'm not really able to go any smaller without things being cut off due to Slack's size constraints. If it is still too large, just open a new issue and I can probably spend a bit more time on this and tweak some things a bit further.

**Comment by jakdept** [comment]
No - I looked at this, and for my use cases at least, this looks great :smile: I think that, while going smaller than it was is kindof necessary if you want to tile next to another window, going smaller than it is probably is not needed.
